
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CHAVEDIR CHAVEESQ ID SEPFrase : ElementosElementos : Elementos FolderElementos : FolderFolder : ID CHAVEDIR empty CHAVEESQFolder : ID CHAVEDIR Subfolder CHAVEESQSubfolder : FolderSubfolder : Folder SEP FolderFolder : ID CHAVEDIR Ficheiro CHAVEESQFicheiro : IDFicheiro : Ficheiro SEP IDempty :'
    
_lr_action_items = {'ID':([0,2,3,5,6,12,13,14,15,16,],[4,4,-3,-2,7,-4,-5,-8,17,4,]),'$end':([1,2,3,5,12,13,14,],[0,-1,-3,-2,-4,-5,-8,]),'CHAVEDIR':([4,7,],[6,6,]),'CHAVEESQ':([6,7,8,9,10,11,12,13,14,17,18,],[-11,-9,12,13,14,-6,-4,-5,-8,-10,-7,]),'SEP':([7,10,11,12,13,14,17,],[-9,15,16,-4,-5,-8,-10,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'Frase':([0,],[1,]),'Elementos':([0,],[2,]),'Folder':([0,2,6,16,],[3,5,11,18,]),'empty':([6,],[8,]),'Subfolder':([6,],[9,]),'Ficheiro':([6,],[10,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> Frase","S'",1,None,None,None),
  ('Frase -> Elementos','Frase',1,'p_frase','parser.py',24),
  ('Elementos -> Elementos Folder','Elementos',2,'p_elementos','parser.py',27),
  ('Elementos -> Folder','Elementos',1,'p_elemento_folder_unica','parser.py',30),
  ('Folder -> ID CHAVEDIR empty CHAVEESQ','Folder',4,'p_folder_vazia','parser.py',33),
  ('Folder -> ID CHAVEDIR Subfolder CHAVEESQ','Folder',4,'p_folder_multfolder','parser.py',40),
  ('Subfolder -> Folder','Subfolder',1,'p_subfolder_empty','parser.py',48),
  ('Subfolder -> Folder SEP Folder','Subfolder',3,'p_subfolder','parser.py',51),
  ('Folder -> ID CHAVEDIR Ficheiro CHAVEESQ','Folder',4,'p_folder_ficheiro','parser.py',55),
  ('Ficheiro -> ID','Ficheiro',1,'p_ficheiro','parser.py',62),
  ('Ficheiro -> Ficheiro SEP ID','Ficheiro',3,'p_ficheiros','parser.py',67),
  ('empty -> <empty>','empty',0,'p_empty','parser.py',79),
]
